"""Add QA table

Revision ID: b530f7048ff2
Revises: 3a2abc6e8224
Create Date: 2026-01-17 23:42:17.258658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b530f7048ff2'
down_revision: Union[str, None] = '3a2abc6e8224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False, comment='紐づくドキュメントID'),
    sa.Column('question_user_id', sa.BigInteger(), nullable=False, comment='質問したユーザー'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='質問本文'),
    sa.Column('answer_text', sa.Text(), nullable=True, comment='回答本文（未回答時はnull）'),
    sa.Column('answer_user_id', sa.BigInteger(), nullable=True, comment='回答したユーザー'),
    sa.Column('status', sa.Enum('PENDING', 'ANSWERED', 'CLOSED', name='qastatus'), server_default='PENDING', nullable=False, comment='対応ステータス'),
    sa.Column('is_faq', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='FAQフラグ'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='質問投稿日時'),
    sa.Column('answered_at', sa.DateTime(), nullable=True, comment='回答日時'),
    sa.ForeignKeyConstraint(['answer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qas')
    # ### end Alembic commands ###
